sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

  fast_finish: true

cache:
  directories:
    - .composer/cache

before_install:
  - alias composer=composer\ -n && composer self-update

install:
  - composer install

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION != hhvm \
      && $TRAVIS_PHP_VERSION != hhvm-nightly \
      && $TRAVIS_PHP_VERSION != 7.0 ]]; then
      cat <<<'
        extension=mongo.so
        extension=redis.so
      ' >> ~/.phpenv/versions/"$(phpenv version-name)"/etc/conf.d/travis.ini
    fi

  - |
    if [[ $TRAVIS_PHP_VERSION = 5.6 ]]; then
      sed '/MockeryPHPUnitIntegration/d' -i ./phpunit.xml.dist
    fi

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email:
    - padraic.brady@gmail.com
    - dave@atstsolutions.co.uk

  irc: irc.freenode.org#mockery
